prometheusOperator:
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false

alertmanager:
  enabled: false

nodeExporter:
  enabled: false

kube-state-metrics:
  enabled: false

prometheus:
  prometheusSpec:
    replicas: 1
    retention: 1d
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi

grafana:
  replicas: 1
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi